### PR TITLE
add new features and convert to sqlite

### PR DESCRIPTION
**Pull request by leefrance**
adds more detailed features and rewrites to use sqlite over geojson

### CODE REVIEW

**Review by jczaplew — COMMENTED** [review]
LGTM! Just out of curiosity what is the motivation for switching from GeoJSON to sqlite?

**Comment by leefrance** [comment]
@jczaplew just for a lighter format..the file size was exceeding the 100mb github limit. Pretty soon I'll have to shift this to an s3 location most likely

**Comment by ghost** [comment]
Have you considered using Git Large File Storage (Git LFS) on GitHub?

**Comment by leefrance** [comment]
@interwebjill no I hadn't but thanks for suggesting it! I'll look into that, might be a good use case for this.

**Pull request merged**
